# Import Library

In [1]:
import numpy as np

# Memasukkan nama alternative

In [ ]:
num_alternatives = int(input("Masukkan jumlah alternative: "))
alternatives = [input(f"Nama Alternative {i+1}: ") for i in range(num_alternatives)]

# Memasukkan jumlah kriteria

In [ ]:
num_criteria = int(input("Masukkan jumlah kriteria: "))

# Memasukkan kriteria dan menentukan jenisnya (beneficial atau non-beneficial)

In [5]:
criteria_info = {}
for i in range(num_criteria):
    criteria_name = input(f"Nama Kriteria {i+1}: ")
    criteria_type = input(f"Tipe Kriteria ({criteria_name}): (b / n): ").lower()
    criteria_info[criteria_name] = criteria_type

Nama Kriteria 1: Jarak
Tipe Kriteria (Jarak): (b / n): n
Nama Kriteria 2: Biaya
Tipe Kriteria (Biaya): (b / n): n
Nama Kriteria 3: Fasilitas
Tipe Kriteria (Fasilitas): (b / n): b
Nama Kriteria 4: Luas kamar
Tipe Kriteria (Luas kamar): (b / n): b


# Memasukkan bobot (weight) setiap kriteria

In [6]:
weights = [float(input(f"Bobot Kriteria {criteria}: ")) for criteria in criteria_info.keys()]

Bobot Kriteria Jarak: 0.4
Bobot Kriteria Biaya: 0.3
Bobot Kriteria Fasilitas: 0.2
Bobot Kriteria Luas kamar: 0.1


# Pembuatan decision matrix

In [7]:
decision_matrix = np.zeros((num_alternatives, num_criteria))
for i in range(num_alternatives):
    for j, criteria in enumerate(criteria_info.keys()):
        decision_matrix[i][j] = float(input(f"Rating Alternative {alternatives[i]} terhadap Kriteria {criteria}: "))

print("\nDecision Matrix:")
print(decision_matrix)

Rating Alternative Apartement SDC terhadap Kriteria Jarak: 300
Rating Alternative Apartement SDC terhadap Kriteria Biaya: 3250000
Rating Alternative Apartement SDC terhadap Kriteria Fasilitas: 22
Rating Alternative Apartement SDC terhadap Kriteria Luas kamar: 36
Rating Alternative Dormitory UMN terhadap Kriteria Jarak: 1400
Rating Alternative Dormitory UMN terhadap Kriteria Biaya: 1288000
Rating Alternative Dormitory UMN terhadap Kriteria Fasilitas: 11
Rating Alternative Dormitory UMN terhadap Kriteria Luas kamar: 25
Rating Alternative Treasure Kost terhadap Kriteria Jarak: 450
Rating Alternative Treasure Kost terhadap Kriteria Biaya: 1650000
Rating Alternative Treasure Kost terhadap Kriteria Fasilitas: 9
Rating Alternative Treasure Kost terhadap Kriteria Luas kamar: 12
Rating Alternative Resident 8 terhadap Kriteria Jarak: 450
Rating Alternative Resident 8 terhadap Kriteria Biaya: 1350000
Rating Alternative Resident 8 terhadap Kriteria Fasilitas: 9
Rating Alternative Resident 8 terhad

# Normalisasi decision matrix

In [8]:
normalized_decision_matrix = np.zeros((num_alternatives, num_criteria))
for j, criteria in enumerate(criteria_info.keys()):
    if criteria_info[criteria] == "b":
        max_val = np.max(decision_matrix[:, j])
        normalized_decision_matrix[:, j] = decision_matrix[:, j] / max_val
    elif criteria_info[criteria] == "n":
        min_val = np.min(decision_matrix[:, j])
        normalized_decision_matrix[:, j] = min_val / decision_matrix[:, j]

print("\nNormalized Decision Matrix:")
print(normalized_decision_matrix)


Normalized Decision Matrix:
[[0.73333333 0.39630769 1.         1.        ]
 [0.15714286 1.         0.5        0.69444444]
 [0.48888889 0.78060606 0.40909091 0.33333333]
 [0.48888889 0.95407407 0.40909091 0.33333333]
 [1.         0.67789474 0.27272727 0.44444444]
 [0.4        0.75764706 0.36363636 1.        ]
 [0.33846154 0.85866667 0.5        0.44444444]
 [0.48888889 0.644      0.68181818 0.25      ]
 [0.48888889 0.644      0.68181818 0.33333333]]


# Kalkulasi weighted normalized decision matrix

In [9]:
weighted_normalized_decision_matrix = normalized_decision_matrix * weights

print("\nWeighted Normalized Decision Matrix:")
print(weighted_normalized_decision_matrix)


Weighted Normalized Decision Matrix:
[[0.29333333 0.11889231 0.2        0.1       ]
 [0.06285714 0.3        0.1        0.06944444]
 [0.19555556 0.23418182 0.08181818 0.03333333]
 [0.19555556 0.28622222 0.08181818 0.03333333]
 [0.4        0.20336842 0.05454545 0.04444444]
 [0.16       0.22729412 0.07272727 0.1       ]
 [0.13538462 0.2576     0.1        0.04444444]
 [0.19555556 0.1932     0.13636364 0.025     ]
 [0.19555556 0.1932     0.13636364 0.03333333]]


# Kalkulasi score di setiap alternatif

In [10]:
scores = np.prod(weighted_normalized_decision_matrix, axis=1)

print("\nScores:")
print(scores)


Scores:
[0.0006975  0.00013095 0.0001249  0.00015265 0.00019721 0.00026449
 0.000155   0.0001288  0.00017173]


# Menentukan best alternatif

In [11]:
best_alternative_index = np.argmax(scores)
best_alternative = alternatives[best_alternative_index]

print("\nHasil Weighted Product Method:")
print(f"Alternatif terbaik: {best_alternative} dengan score {scores[best_alternative_index]}")


Hasil Weighted Product Method:
Alternatif terbaik: Apartement SDC dengan score 0.0006975015384615385
